"""Write the replay-recorder specs viz/specs/*.yaml (rrp.viz.record, D-131). Episode choices come from the recorded
eval rows (archived research/tracks/room.md "replays"): per cell one success and one failure where the recorded rows have them,
chosen inside the FIRST batch of 16 of their seed set (the ladder's flow/BC noise generator is shared across batches,
so a later seed needs every earlier batch re-run). Paths are relative to the peer code dir (artifacts -> shared store)
except the host-only recorded rows, copied to $VIZ_REC (/dev/shm/rrp-brandonin/viz_recorded).

    rrp viz specs          # writes viz/specs/{arm,legged,physics,dual}.yaml
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
REC = "/dev/shm/rrp-brandonin/viz_recorded"
R = "artifacts/runs"
L8 = f"{R}/legged8"


def q(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "null"
    if isinstance(v, (int, float)):
        return json.dumps(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        return "[" + ", ".join(q(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{k}: {q(x)}" for k, x in v.items()) + "}"
    raise TypeError(v)


def dump(entries, header: str) -> str:
    out = [f"# {header}", "# generated by `rrp viz specs`; run on the PEER: python -m rrp.cli viz record --spec <this> --out ...",
           "entries:"]
    for e in entries:
        first = True
        for k, v in e.items():
            out.append(("  - " if first else "    ") + f"{k}: {q(v)}")
            first = False
    return "\n".join(out) + "\n"


# ------------------------------------------------------------------ ARM
LINS = {  # variant -> (lineage code, file tag, dagger dir prefix)
    "frozen_sem_s1": ("jointfix", "", ""), "semfix_s1": ("sfjf", "sf", "sfjf_"), "nosem_s1": ("nsjf", "ns", "nsjf_"),
    "frozen_sem_s2": ("sejf2", "se2", "sejf2_"), "semfix_s2": ("sfjf2", "sf2", "sfjf2_"), "nosem_s2": ("nsjf2", "ns2", "nsjf2_")}
# (variant, body) -> {seed_start: [seeds]}: one success + one failure per grasp version where the batch has them
# (from the recorded v1/v2 outcomes of the first batch; see the table in archived research/tracks/room.md)
ARM_SEEDS = {
    ("frozen_sem_s1", "panda_pg2"): {3000000: [3000002, 3000000]},
    ("frozen_sem_s1", "parm6_tf3"): {3000000: [3000019, 3000005, 3000003]},
    ("semfix_s1", "panda_pg2"): {3000000: [3000000, 3000005]},
    ("semfix_s1", "parm6_tf3"): {3000000: [3000004, 3000011]},
    ("nosem_s1", "panda_pg2"): {3000000: [3000000, 3000001]},
    ("nosem_s1", "parm6_tf3"): {3000000: [3000010, 3000003]},
    ("frozen_sem_s2", "panda_pg2"): {3000000: [3000002, 3000000]},
    ("frozen_sem_s2", "parm6_tf3"): {3000000: [3000005, 3000010]},
    ("semfix_s2", "panda_pg2"): {3000000: [3000000, 3000014]},
    ("semfix_s2", "parm6_tf3"): {3000000: [3000005, 3000010]},
    ("nosem_s2", "panda_pg2"): {3000000: [3000000, 3000001]},
    ("nosem_s2", "parm6_tf3"): {3000000: [3000003, 3000012]},
}
BC_SEEDS = {"panda_pg2": {3000000: [3000000], 3000100: [3000111]}, "parm6_tf3": {3000000: [3000003, 3000004]}}
BC = f"{R}/latent_slice1_b1fix/baseline_direct_action/seed1701/source/policy.pt"
GV_REFS = {"v1": ["D-091", "D-095"], "v2": ["D-110", "D-127"]}
V1_CAVEAT = "grasp_v1: grasps may hold by interpenetration (D-108); superseded by grasp_v2 for new results (D-110)"
CODE_CAVEAT = ("re-run with the current main code (the ladder moved to rrp.harness.eval.ladder in D-126, same CLI); "
               "the recorded rows came from earlier commits; meta.reproduced reports the check")


def arm_entries():
    out = []
    for (var, body), sets in ARM_SEEDS.items():
        lin, tg, dp = LINS[var]
        for gv in ("v1", "v2"):
            for S, seeds in sets.items():
                name = f"generated_zero_flow{tg}gdag2h_rz{tg}gendag3_noqd_s{S}.jsonl"
                rec = f"{R}/ladder_v1/{body}/{name}" if gv == "v1" else f"{R}/armexpert_gc2eval/grasp_v2/{body}/{name}"
                caveat = (V1_CAVEAT + "; " if gv == "v1" else "") + CODE_CAVEAT
                if var == "frozen_sem_s1" and body == "parm6_tf3" and gv == "v2":
                    caveat += "; frozen sem s1 collapses on tf3 under grasp_v2 (70 -> 9/90, D-127)"
                out.append(dict(
                    id=f"arm-r2-{var}-{body}-g{gv}-set{S - 3000000:03d}", harness="ladder", family="arm", task="pick_place",
                    body=body, route="R2_deployable_flow_to_system0", variant=var, condition=f"grasp_{gv}",
                    source_label=f"learned:ladder_flow_{lin}_gdag2h/policy.pt -> system0 ladder_rz_{lin}_gendag3_noqd",
                    decision_refs=GV_REFS[gv] + (["D-078"] if lin == "jointfix" else []), caveat=caveat,
                    env={"RRP_GRASP_CONTACT": gv}, threads=2,
                    args=dict(route="generated", robot=body, n=30, seed_start=S, flow=f"{R}/ladder_flow_{lin}_gdag2h/policy.pt",
                              rep=f"{R}/ladder_rz_{lin}_gendag3_noqd/representation.pt", prev_action="zero", batch=16),
                    seeds=seeds, recorded=dict(file=rec),
                    pca=dict(kind="arm_npz", glob=f"{R}/ladder_dagger_{dp}gen3/*.npz", n=4000)))
    for body, sets in BC_SEEDS.items():
        for gv in ("v1", "v2"):
            for S, seeds in sets.items():
                out.append(dict(
                    id=f"arm-bc-direct1701-{body}-g{gv}-set{S - 3000000:03d}", harness="ladder", family="arm", task="pick_place",
                    body=body, route="BC_direct_action", variant="bc_direct1701_final", condition=f"grasp_{gv}",
                    source_label="bc:latent_slice1_b1fix/baseline_direct_action/seed1701/source/policy.pt (direct1701_final)",
                    decision_refs=["D-110", "D-127"], caveat=(V1_CAVEAT + "; " if gv == "v1" else "") + CODE_CAVEAT,
                    env={"RRP_GRASP_CONTACT": gv}, threads=2,
                    args=dict(route="learned", robot=body, n=30, seed_start=S, policy=BC, policy_label="learned:direct1701_final",
                              batch=16),
                    seeds=seeds,
                    recorded=dict(file=f"{R}/armexpert_gc2eval/grasp_{gv}/{body}/learned_bc_direct1701_final_s{S}.jsonl")))
    for body, seeds in (("panda_pg2", [3000000, 3000001]), ("parm6_tf3", [3000003, 3000004])):
        for gv in ("v1", "v2"):
            out.append(dict(
                id=f"arm-teacher-v2-{body}-g{gv}", harness="arm_teacher", family="arm", task="pick_place", body=body,
                route="scripted_teacher", variant="teacher_v2_minjerk", condition=f"grasp_{gv}",
                source_label="scripted_teacher:pick_place_v2_minjerk", decision_refs=["D-097", "D-110"],
                caveat="privileged scripted teacher; the recorded v2 teacher has no failures on these bodies (4810/4811)",
                env={"RRP_GRASP_CONTACT": gv}, threads=1, args=dict(robot=body, version="v2", max_steps=600), seeds=seeds,
                recorded=dict(file=f"{REC}/armexpert_grasp/final_grasp{gv}_18bodies.jsonl.gz")))
    # semantic edits (D-091/D-095 suites; grasp_v1 as recorded): control / rebind / goal shift on one scene
    for var, body, shard, seed in (("semfix_s1", "parm6_tf3", "parm6", 3000003), ("nosem_s1", "parm6_tf3", "parm6", 3000003),
                                   ("semfix_s2", "parm6_tf3", "parm6", 3000003), ("nosem_s2", "parm6_tf3", "parm6", 3000003),
                                   ("semfix_s1", "panda_pg2", "panda", 3000000), ("nosem_s2", "panda_pg2", "panda", 3000000)):
        lin, _tg, dp = LINS[var]
        acc = {"nsjf": "nosem"}.get(lin, lin)
        out.append(dict(
            id=f"arm-edit-{var}-{body}", harness="arm_edit", family="arm", task="pick_place", body=body,
            route="R2_deployable_flow_to_system0", variant=var, condition="edit",
            source_label=f"learned:ladder_flow_{lin}/snap_final_s20000.pt -> system0 ladder_rz_{lin}_gendag1_noqd",
            decision_refs=["D-074", "D-091", "D-095"], caveat=V1_CAVEAT + "; " + CODE_CAVEAT,
            env={"RRP_GRASP_CONTACT": "v1", "OMP_NUM_THREADS": "1"}, threads=1,
            args=dict(route="generated", robot=body, flow=f"{R}/ladder_flow_{lin}/snap_final_s20000.pt",
                      rep=f"{R}/ladder_rz_{lin}_gendag1_noqd/representation.pt", max_steps=400),
            conditions=["control", "rebind_desc", "goal_shift"], seeds=[seed],
            recorded=dict(file=f"{R}/acceptance_arm{acc}_gen_{shard}/shard0/semantic_rows_generated.jsonl"),
            pca=dict(kind="arm_npz", glob=f"{R}/ladder_dagger_{dp}gen1/*.npz", n=4000)))
    return out


# ------------------------------------------------------------------ LEGGED (W8 contact_v2) + robustness
BODIES = {"anymal_c": ("anymal_c", [10002, 10017]), "go2": ("go2", [10007, 10003]), "t1sl": ("t1", [10019, 10000])}
T1_CAVEAT = ("t1 (sourced limits): dataset fails the D-112 slip gate (86.2% < 95%), tracker w8d fails lab forward 0.72 and "
             "exceeds joint limits (margin -0.053) (D-113/D-114); learned controllers fall often (D-124)")


def legged_entries():
    out = []
    for B, (body, seeds) in BODIES.items():
        cav = T1_CAVEAT if B == "t1sl" else None
        for v in ("semfix", "nosem"):
            d = f"{L8}/legged8-{B}-{v}"
            for edit, cond in (("none", "ctx_unedited"), ("halt", "ctx_halt"), ("mirror_inactive", "ctx_mirror_inactive_control")):
                args = dict(flow=f"{d}/train_flow_s0/snap_s4000.pt", edit=edit, t_edit=2.0, max_s=5.0)
                if v == "nosem":
                    args["posthoc_probe"] = f"{d}/probes_s0/probe_posthoc.pt"
                e = dict(id=f"leg-ctx-{B}-{v}_s0-{edit}", harness="legged", family="legged", task="waypoint_contact",
                         body=body, route="R2_deployable_flow_to_system0", variant=f"{v}_s0", condition=cond,
                         source_label=f"learned:legged8-{B}-{v}/train_flow_s0/snap_s4000.pt",
                         decision_refs=["D-105", "D-113", "D-124"], env={"RRP_CONTACT_MODEL": "contact_v2", "OMP_NUM_THREADS": "1"},
                         threads=2, args=args, seeds=seeds,
                         recorded=dict(file=f"{d}/edits-ctx_s0/r2ctx_v2_{v}_{body}_s0_snap_s4000/{edit}.jsonl"),
                         pca=dict(kind="legged_rep", rep=f"{d}/train_rep_s0/representation.pt", body=body, n=2560))
                if cav:
                    e["caveat"] = cav
                out.append(e)
        dd = f"{L8}/legged8-{B}-v2data"
        ref_seeds = [10002] + ([10019] if B == "t1sl" else [])
        out.append(dict(id=f"leg-ref-{B}-teacher", harness="legged", family="legged", task="waypoint_contact", body=body,
                        route="scripted_teacher", variant="teacher", condition="r2_reference",
                        source_label=f"scripted_teacher:waypoint (privileged) + learned_tracker:{body}:contact_v2",
                        decision_refs=["D-124"], env={"RRP_CONTACT_MODEL": "contact_v2", "OMP_NUM_THREADS": "1"}, threads=2,
                        args=dict(max_s=60.0), seeds=ref_seeds, **({"caveat": cav} if cav else {}),
                        recorded=dict(file=f"{dd}/eval_r2-teacher_s0/{body}/teacher_v2_teacher_{body}.jsonl")))
        out.append(dict(id=f"leg-ref-{B}-bc", harness="legged", family="legged", task="waypoint_contact", body=body,
                        route="BC_direct_action", variant="bc_s0", condition="r2_reference",
                        source_label=f"bc:legged8-{B}-v2data/train_bc_s0/policy.pt",
                        decision_refs=["D-124"], env={"RRP_CONTACT_MODEL": "contact_v2", "OMP_NUM_THREADS": "1"}, threads=2,
                        args=dict(bc=f"{dd}/train_bc_s0/policy.pt", max_s=60.0), seeds=ref_seeds,
                        **({"caveat": cav + "; t1 BC 0/30"} if cav else {}),
                        recorded=dict(file=f"{dd}/eval_r2-bc_s0/{body}/bc_v2_bc_{body}.jsonl")))
    # robustness break points (D-108/D-112), anymal_c training seed 0, final policy.pt, 60 s, 1 torch thread
    for key, seeds in (("push_dv=1", [10001]), ("friction=0.4", [10010]), ("terrain_m=0.08", [10003, 10000])):
        for v in ("semfix", "nosem"):
            out.append(dict(
                id=f"leg-robust-anymal_c-{v}_s0-{key.replace('=', '')}", harness="legged_robust", family="legged",
                task="waypoint_contact", body="anymal_c", route="R2_deployable_flow_to_system0", variant=f"{v}_s0",
                condition=f"robust_{key}", source_label=f"learned:legged8-anymal_c-{v}/train_flow_s0/policy.pt",
                decision_refs=["D-108", "D-112"],
                caveat="the seed-0 sweep ran on the host venv (numpy 2.5.3) before D-115; this re-run uses the peer venv",
                env={"RRP_CONTACT_MODEL": "v2", "OMP_NUM_THREADS": "1"}, threads=1,
                args=dict(flow=f"{L8}/legged8-anymal_c-{v}/train_flow_s0/policy.pt", condition_key=key, max_s=60.0),
                seeds=seeds, recorded=dict(file=f"{R}/robust/legged_anymal_c/{v}/anymal_c/{key}.jsonl"),
                pca=dict(kind="legged_rep", rep=f"{L8}/legged8-anymal_c-{v}/train_rep_s0/representation.pt", body="anymal_c",
                         n=2560)))
    return out


# ------------------------------------------------------------------ PHYSICS: trackers (v1 vs v2 contact) + grasp rig
TRK = {  # body -> [(tag, actor, contact, extra env, recorded file stem)]
    "anymal_c": [("v1trk_physv1", "artifacts/trackers/anymal_c/actor.pt", "v1", {}, "anymal_c_v1trk_physv1"),
                 ("v2trk_physv2", "artifacts/trackers/anymal_c/contact_v2/actor.pt", "v2", {}, "anymal_c_v2trk_physv2")],
    "go2": [("v1trk_physv1", "artifacts/trackers/go2/actor.pt", "v1", {}, "go2_v1trk_physv1"),
            ("v2cf2_physv2", "artifacts/trackers/go2/contact_v2/actor.pt", "v2", {}, "go2_v2cf2_physv2")],
    "t1": [("v1trk_physv1", "artifacts/trackers/t1/actor.pt", "v1", {"RRP_ACTUATOR_LIMITS": "legacy_gains_v0"}, "t1_v1trk_physv1"),
           ("w8d_physv2", "artifacts/trackers/t1/contact_v2/actor.pt", "v2", {}, "t1_w8d-ideal_physv2")],
}


def physics_entries():
    out = []
    for body, rows in TRK.items():
        for tag, actor, contact, env, stem in rows:
            out.append(dict(
                id=f"trk-{body}-{tag}-forward", harness="tracker_val", family="legged", task="tracker_validation", body=body,
                route="tracker_only", variant=tag, condition=f"contact_{contact}",
                source_label=f"learned_tracker:{body}:{tag}", decision_refs=["D-093", "D-101", "D-103"],
                caveat=("t1 v1 tracker: legacy (inflated) torque limits, D-107" if body == "t1" and contact == "v1" else
                        (T1_CAVEAT if body == "t1" else None)),
                env=env, threads=1, args=dict(kind="learned", actor=actor, contact=contact, trial="forward"), seeds=[1000],
                recorded=dict(file=f"{REC}/contact_v2_val/{stem}.json", path=["episodes", "forward"], index_from=1000)))
    for gv in ("v1", "v2"):
        for grip in ("pg2", "tf3"):
            for fs in (1.0, 0.05):
                out.append(dict(
                    id=f"rig-{grip}-g{gv}-mu{str(fs).replace('.', 'p')}", harness="grasp_rig", family="arm", task="grasp_rig",
                    body=f"{grip}_gripper_rig", route="scripted_rig", variant=f"grasp_{gv}", condition=f"friction_x{fs}",
                    source_label="scripted_teacher:grasp_rig (close, 10 cm lift, mass ramp)", decision_refs=["D-108", "D-110"],
                    caveat="the rig has only a cube case; the peg case is the support_insert v1 vs v2.1 dual replay (D-125)",
                    env={}, threads=1, args=dict(version=gv, gripper=grip, friction_scale=fs, yaw_deg=0.0), seeds=[0],
                    recorded=dict(file=f"{REC}/armexpert_grasp/rig.jsonl")))
    return out


# ------------------------------------------------------------------ DUAL (W12)
def dual_entries():
    out = []
    for task in ("support_insert", "handover"):
        for pair in ("parm5_pg2__parm5_pg2", "panda_pg2__ur5e_pg2"):
            out.append(dict(
                id=f"dual-{task}-v3-{pair}", harness="dual_teacher", family="dual", task=task, body=pair,
                route="scripted_teacher", variant="dual_teacher_v3", condition="grasp_v2.1_smoke",
                source_label=f"scripted_teacher:dual_{task}_v3 (smoke)", decision_refs=["D-125", "D-130"],
                caveat="smoke-level (2 pairs x 3 seeds); teacher v3 still fails the smoothness gates on parm5 handover (D-130)",
                env={"RRP_GRASP_CONTACT": "v2.1"}, threads=1,
                args=dict(task=task, pair=pair, teacher_version="v3", max_steps=1200), seeds=[0, 1],
                recorded=dict(file=f"{R}/w12_smoke/{task}_v3.jsonl")))
    for gv, f in (("v1", "support_insert_v1_clean"), ("v2.1", "support_insert_v21_clean")):
        out.append(dict(
            id=f"dual-support_insert-v2teacher-peg-g{gv.replace('.', '')}", harness="dual_teacher", family="dual",
            task="support_insert", body="parm5_pg2__parm5_pg2", route="scripted_teacher", variant="dual_teacher_v2",
            condition=f"grasp_{gv}_peg", source_label="scripted_teacher:dual_support_insert", decision_refs=["D-125"],
            caveat=("grasp_v2.1 peg-grip failure: the peg slides ~2.5 cm through the parallel-jaw grip (grip ~16-20 N)"
                    if gv == "v2.1" else "grasp_v1 reference for the same pair and seed"),
            env={"RRP_GRASP_CONTACT": gv}, threads=1,
            args=dict(task="support_insert", pair="parm5_pg2__parm5_pg2", max_steps=1200), seeds=[0],
            recorded=dict(file=f"{R}/w12_dualaudit/{f}.jsonl")))
    return out


def main(argv=None):
    d = ROOT / "viz" / "specs"
    d.mkdir(parents=True, exist_ok=True)
    from rrp.harness.yamlmini import load
    for name, fn, hdr in (("arm", arm_entries, "arm: R2 / BC / teacher v2 under grasp_v1 and grasp_v2, semantic edits"),
                          ("legged", legged_entries, "legged W8 contact_v2: context edits, teacher/BC refs, robustness"),
                          ("physics", physics_entries, "tracker validation v1 vs v2 contact, grasp rig v1 vs v2"),
                          ("dual", dual_entries, "dual W12: teacher v3 smoke, grasp_v2.1 peg failure")):
        es = [{k: v for k, v in e.items() if v is not None} for e in fn()]
        txt = dump(es, hdr)
        assert load(txt)["entries"] == es, name
        (d / f"{name}.yaml").write_text(txt)
        print(name, len(es), "entries", sum(len(e["seeds"]) * len(e.get("conditions", [1])) for e in es), "episodes")

