// GENERATED by scripts/export_ui_types.py from src/rrp/service/schemas.py -- do not edit by hand.

export const MESSAGE_KINDS = ["session_snapshot", "state_update", "graph_committed", "command_rejected", "command_accepted", "probe_result", "resource_update", "mode_changed", "intervention", "event_request", "event_cancelled", "debug_override", "session_reset", "frame"] as const;
export type MessageKind = (typeof MESSAGE_KINDS)[number];

/** mirrors rrp.service.schemas.CreateSession */
export interface CreateSession {
  robot: string;
  task?: string;
  seed?: number;
}

/** mirrors rrp.service.schemas.Command */
export interface Command {
  type: "step" | "run" | "pause" | "reset" | "joint_target" | "ee_target" | "teleport" | "request_event" | "cancel_event" | "set_mode" | "debug_force_success" | "replay";
  n?: number;
  group?: string | null;
  values?: Array<number> | null;
  pos?: Array<number> | null;
  yaw?: number;
  body?: string | null;
  event_id?: string | null;
  expected_version?: number | null;
  mode?: string | null;
  policy?: string | null;
  seed?: number | null;
  confirm?: boolean;
  request_id?: string | null;
}

/** mirrors rrp.service.schemas.GraphEditRequest */
export interface GraphEditRequest {
  expected_version: number;
  request_id: string;
  operations: Array<Record<string, unknown>>;
}

/** mirrors rrp.service.schemas.LayoutRequest */
export interface LayoutRequest {
  positions: Record<string, Array<number>>;
}

/** mirrors rrp.service.schemas.ProbeRequest */
export interface ProbeRequest {
  query: "visible" | "looking_at" | "focused_on" | "acting_on" | "held_by" | "manipulator_tasks" | "relative_pose" | "distance" | "active_frame" | "contact_mode" | "desired_delta" | "feasibility" | "uncertainty" | "object_qa";
  subject?: string | null;
  object?: string | null;
  question?: string | null;
}

export type CommandType = Command["type"];
export type ProbeQuery = ProbeRequest["query"];
