"""Transmitted system-i -> system-0 packet (R38).

`LatentActionChunk` carries the ACTUAL latent values z[k, m, d] generated by system i. System 0 consumes exactly
this tensor (declared transform: float32 serialization). Metadata is limited to opaque addresses, timing, provenance
and compatibility; the strict schema rejects any semantic field (focused object, task description, target pose,
desired effect, solved dependencies ...). The existing native `ActionChunk` is unchanged and remains the old-format
path for baselines.
"""
from __future__ import annotations

import time
from typing import Literal

import numpy as np
from pydantic import Field, model_validator

from .base import Strict, NDArray
from .errors import ControllerRejection, StaleActionError

LATENT_SCHEMA = "latent-action-1.0"


class AssemblyHandle(Strict):
    """Opaque controllable-assembly address: declared identity only (spec hash + structural address)."""
    handle: str = Field(pattern=r"^asm:[0-9a-f]{16}:[A-Za-z0-9_/:.-]+$")
    robot_index: int = Field(ge=0)


class EntityHandle(Strict):
    """Opaque entity address in the packet's registry (canonical slot index). No features, labels or names."""
    handle: str = Field(pattern=r"^ent:[0-9]+$")


class LatentActionChunk(Strict):
    schema_version: Literal["latent-action-1.0"] = LATENT_SCHEMA
    latent_space_version: str
    realizer_compat_version: str
    z: NDArray                            # [K, M, D] float32 — the supervised, transmitted, consumed tensor
    knot_times: list[float]               # seconds relative to valid_from, strictly increasing, len K
    assemblies: list[AssemblyHandle]      # len M (order = packet assembly axis)
    assembly_mask: list[bool]
    entity_registry: list[EntityHandle] = Field(default_factory=list)
    observation_id: str
    graph_version: int = Field(ge=0)
    runtime_version: int = Field(ge=0)
    robot_spec_hash: str
    generated_at: float
    valid_from: float                     # simulation/controller time the knot times are relative to
    valid_until: float
    source: Literal["learned", "target_encoder_oracle", "debug", "replay"]
    policy_version: str
    sampling: dict = Field(default_factory=dict)   # seed, nfe, sampler — provenance only

    @model_validator(mode="after")
    def _check(self):
        z = self.z
        if z.ndim != 3:
            raise ValueError("z must be [K, M, D]")
        if z.dtype.kind != "f" or not np.isfinite(z).all():
            raise ValueError("z must be finite floating point")
        K, M, _ = z.shape
        if len(self.knot_times) != K or any(b <= a for a, b in zip(self.knot_times, self.knot_times[1:])):
            raise ValueError("knot_times must have length K and be strictly increasing")
        if len(self.assemblies) != M or len(self.assembly_mask) != M:
            raise ValueError("assembly handles/mask must match the M axis")
        if len({a.handle for a in self.assemblies}) != M:
            raise ValueError("duplicate assembly handle (two owners for one assembly)")
        if self.valid_until <= self.valid_from:
            raise ValueError("empty validity interval")
        return self

    def to_bytes(self) -> bytes:
        return self.model_dump_json().encode()

    @classmethod
    def from_bytes(cls, b: bytes) -> "LatentActionChunk":
        return cls.model_validate_json(b)


def check_packet(p: LatentActionChunk, *, latent_space_version: str, realizer_compat_version: str,
                 robot_spec_hash: str, now: float, graph_version: int | None = None,
                 owned_assemblies: set[str] | None = None) -> None:
    """System-0 admission. Version/staleness failures are rejections, never silent re-interpretation."""
    if p.latent_space_version != latent_space_version:
        raise ControllerRejection(f"latent space {p.latent_space_version} != {latent_space_version}",
                                  code="latent_space_mismatch")
    if p.realizer_compat_version != realizer_compat_version:
        raise ControllerRejection("realizer compatibility mismatch", code="realizer_mismatch")
    if p.robot_spec_hash != robot_spec_hash:
        raise ControllerRejection("packet generated for another body", code="robot_spec_mismatch")
    if now > p.valid_until:
        raise StaleActionError("packet expired", reasons=["expired"])
    if now < p.valid_from - 1e-9:
        raise ControllerRejection("packet not yet valid", code="not_yet_valid")
    if graph_version is not None and p.graph_version != graph_version:
        raise StaleActionError("packet generated for an older task graph", reasons=["stale_graph_version"])
    if owned_assemblies is not None:
        bad = [a.handle for a, m in zip(p.assemblies, p.assembly_mask) if m and a.handle not in owned_assemblies]
        if bad:
            raise ControllerRejection(f"packet addresses assemblies not owned by this system 0: {bad}",
                                      code="ownership")
