"""Emit ui/src/transport/types.ts from the pydantic request schemas in rrp.service.schemas.

Run: .venv/bin/python scripts/export_ui_types.py  (output is committed; CI can diff it)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from rrp.service import schemas  # noqa: E402

MODELS = [schemas.CreateSession, schemas.Command, schemas.GraphEditRequest, schemas.LayoutRequest,
          schemas.ProbeRequest]


def ts_type(s: dict) -> str:
    if "anyOf" in s:
        return " | ".join(dict.fromkeys(ts_type(x) for x in s["anyOf"]))
    if "enum" in s:
        return " | ".join(json.dumps(v) for v in s["enum"])
    if "const" in s:
        return json.dumps(s["const"])
    t = s.get("type")
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        return f"Array<{ts_type(s.get('items', {}))}>"
    if t == "object":
        ap = s.get("additionalProperties")
        if isinstance(ap, dict):
            return f"Record<string, {ts_type(ap)}>"
        return "Record<string, unknown>"
    return "unknown"


def emit_model(m) -> str:
    sch = m.model_json_schema()
    req = set(sch.get("required", []))
    lines = [f"/** mirrors rrp.service.schemas.{m.__name__} */", f"export interface {m.__name__} {{"]
    for name, prop in sch["properties"].items():
        opt = "" if name in req else "?"
        lines.append(f"  {name}{opt}: {ts_type(prop)};")
    lines.append("}")
    return "\n".join(lines)


def main() -> str:
    parts = ["// GENERATED by scripts/export_ui_types.py from src/rrp/service/schemas.py -- do not edit by hand.",
             "",
             "export const MESSAGE_KINDS = " + json.dumps(list(schemas.public_message_kinds())) + " as const;",
             "export type MessageKind = (typeof MESSAGE_KINDS)[number];",
             ""]
    for m in MODELS:
        parts.append(emit_model(m))
        parts.append("")
    parts.append('export type CommandType = Command["type"];')
    parts.append('export type ProbeQuery = ProbeRequest["query"];')
    out = "\n".join(parts) + "\n"
    dst = REPO / "ui" / "src" / "transport" / "types.ts"
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(out)
    return out


if __name__ == "__main__":
    print(main())
