"""Tile the four context-halt clips of one (body, training seed, eval seed) into a labelled 2x2 video:
top = fixed sem (unedited | halt), bottom = nosem (unedited | halt). Writes artifacts/video/<date>_learned_ctxhalt_... .mp4 and one
INDEX.md line with the measured forward progress in the edit window (t=2-8 s) from the rendered rows.
usage: t1_edits_tile.py RUNDIR BODY TRAINSEED EVALSEED KIND [OUTDIR (default artifacts/video)]
env TILE_TRACK (default "t1_edits track") and TILE_NOTE (appended to the INDEX line; e.g. physics/tracker) label reuse by W8."""
import os
import datetime as dt
import json
import math
import sys
from pathlib import Path

import imageio
import numpy as np
from PIL import Image, ImageDraw

V, body, k, seed, kind = Path(sys.argv[1]), sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5]
cells, info = {}, {}
for v in ("fixsem", "nosem"):
    for ed in ("none", "halt"):
        mp4 = sorted((V / f"{v}-{ed}").glob("*.mp4"))
        row = json.loads(open(V / f"{v}-{ed}.jsonl").readline())
        tr = [x for x in row["trace"] if x["t"] >= 2.0 - 1e-6]
        x0, y0, a0 = tr[0]["pose"]; x1, y1, _ = tr[-1]["pose"]
        fwd = math.cos(a0) * (x1 - x0) + math.sin(a0) * (y1 - y0)
        cells[(v, ed)] = [np.asarray(f) for f in imageio.mimread(mp4[-1], memtest=False)]
        info[(v, ed)] = dict(src=row["source"], fwd=fwd, fell=bool(row["fell"]))
n = min(len(c) for c in cells.values())


def lab(img, text, bad):
    im = Image.fromarray(img).convert("RGB"); d = ImageDraw.Draw(im)
    d.rectangle([0, im.height - 20, im.width, im.height], fill=(120, 0, 0) if bad else (0, 60, 0))
    d.text((6, im.height - 16), text, fill=(255, 255, 255)); return np.asarray(im)


frames = []
for i in range(n):
    rows = []
    for v in ("fixsem", "nosem"):
        rr = []
        for ed in ("none", "halt"):
            I = info[(v, ed)]
            rr.append(lab(cells[(v, ed)][i], f"{v.upper()} {'UNEDITED' if ed == 'none' else 'CTX HALT @2s'} | fwd t2-8s {I['fwd']:.2f} m"
                          + (" | FELL" if I["fell"] else ""), I["fell"]))
        rows.append(np.concatenate(rr, 1))
    fr = np.concatenate(rows, 0)
    if os.environ.get("TILE_BANNER"):                 # a caveat drawn on every frame (e.g. W8 t1 gate exception)
        im = Image.fromarray(fr).convert("RGB"); d = ImageDraw.Draw(im)
        d.rectangle([0, 0, im.width, 16], fill=(150, 90, 0)); d.text((6, 3), os.environ["TILE_BANNER"], fill=(255, 255, 255))
        fr = np.asarray(im)
    frames.append(fr)
src = {v: info[(v, "none")]["src"] for v in ("fixsem", "nosem")}
name = f"{dt.date.today()}_learned_ctxhalt_{body}_trainseed{k}_s{seed}_fixsem-vs-nosem_{kind}.mp4"
OD = Path(sys.argv[6]) if len(sys.argv) > 6 else Path("artifacts/video")
out = OD / name
imageio.mimsave(out, frames, fps=5, quality=6)   # source frames are ~5 per sim second: real time
d = {f"{v}_{ed}": round(info[(v, ed)]["fwd"], 3) for v in ("fixsem", "nosem") for ed in ("none", "halt")}
line = (f"- `{name}` — CONTEXT-HALT side by side ({os.environ.get('TILE_TRACK', 't1_edits track')}), {body}, training seed {k}, dev seed {seed}, 8 s cap, halt task view from t=2 s "
        f"(packet regenerated by system i; no z edit). top = learned:{src['fixsem'].removeprefix('learned:')} (FIXED sem, DEPLOYABLE R2), "
        f"bottom = learned:{src['nosem'].removeprefix('learned:')} (nosem, DEPLOYABLE R2); left unedited, right halt. Forward progress t=2-8 s (m): "
        f"fixsem {d['fixsem_none']:.2f} → {d['fixsem_halt']:.2f}, nosem {d['nosem_none']:.2f} → {d['nosem_halt']:.2f}; "
        f"falls: {', '.join(f'{a}-{b}' for (a, b), I in info.items() if I['fell']) or 'none'}. Clip type: {kind}.{(' ' + os.environ['TILE_NOTE']) if os.environ.get('TILE_NOTE') else ''}\n")
open(OD / "INDEX.md", "a").write(line)
print(line)
